# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 19 Jan 2017 21:04:10 +0000
*	@ALL	1
*	wikiadmin	16
justus:*	@ALL	4
justus:*	@user	16
