<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: wikiadmin
 * Date: Mon, 06 Feb 2017 23:13:29 +0100
 */

$conf['title'] = 'Justus';
$conf['template'] = 'dokuwikiMFR0';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
