<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Thu, 19 Jan 2017 20:55:33 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
